### ISSUE TITLE
Pay or play?

### ISSUE THREAD

**Issue by EtherOr** [pkamb/PowerKey#39]
I downloaded PowerKey which was advertised for free:
http://osxdaily.com/2013/04/26/delete-key-mac-forward-del/
But the readme.md file says I must pay or modify my Mac's Gatekeeper security settings. 

## Purchase and Download
The release version of `PowerKey.app` can be [purchased via Gumroad](https://gumroad.com/l/powerkey).
https://gumroad.com/l/powerkey
The release version of PowerKey is signed with our DeveloperID, making it easier to run by default on Mac OS X. Purchasing the code-signed release version of PowerKey will allow you to run the app without modifying your Mac's Gatekeeper security settings.

I am new to Mac and don't know if I want to do that. Nonetheless, I do want forward-delete via the power key your way, if not available another way. I don't even know what file to run to install the app.

**Comment by alice0meta** [comment]
[ disclaimer: I'm not involved in this project; just visiting to install it on a new laptop ]

Modifying Gatekeeper security settings is safe if you know you can trust the app; and you can know you can trust this app because it has lots of stars and forks on github and nobody is complaining about it being untrustworthy.

If you want it free, make sure https://itunes.apple.com/us/app/xcode/id497799835 is installed (large download, I know), then go to https://github.com/pkamb/PowerKey/releases/latest ; download Source code (zip) ; unzip and double-click PowerKey.xcodeproj ; follow instructions at http://stackoverflow.com/a/7802992 to make an exported app (don't bother signing it) ; find the exported PowerKey.app ; move it to /Applications . It's a bit involved; I'm not sure if it has to be.

**Comment by pkamb** [comment]
@EtherOr sorry for the confusion from the OS X Daily article, which is now a bit outdated.

Starting in version 1.5 I began signing the app with my DeveloperID, to avoid the frequent confusion around modifying Gatekeeper Security on your Mac. As part of that I, I also started charging for the pre-built app so I could play around with and test the Gumroad platform for app distribution.

The pre-built version of PowerKey is currently available for a few bucks via Gumroad:

https://gum.co/powerkey

It's also still open source and available to be installed by downloading the source from Github and building from Xcode.

Thank you @alice0meta for the directions for building from source via Xcode! You'll want to download the source files from Github, open the `PowerKey.xcodeproj` file, and build via Xcode to produce the app.
