### ISSUE TITLE
Memory Leak?

### ISSUE THREAD

**Issue by rrhill** [pkamb/PowerKey#45]
I created PowerKey with Xcode. It has a warning plus analysis says it may have a memory leak? It works regardless. I am planning on buying the app rather than use my own compiled version. Just wanted to make sure it worked first. By the by, I'm using Xcode 8 and running macOS (Sierra). If you were to update the code, would the purchased version get updated? Does it check for updates? IS the update free? Comment on the memory leak and warnings?

**Comment by pkamb** [comment]
Hello, I've cleaned up this memory leak warning in [version 1.5.2](https://github.com/pkamb/PowerKey/releases/tag/v1.5.2
). Thanks for letting me know. These memory leaks and/or false warnings in event taps can be a bit tricky due to the rules and method naming conventions when returning events that will be released by the system.

I do update the latest release on Gumroad. Previous customers should then be notified by email that an update is available, and the update is free. However, to keep the app extremely simple I have not added an automatic update mechanism at this time.

Thanks for using PowerKey!
