### ISSUE TITLE
Powerkey too slow

### ISSUE THREAD

**Issue by harvestnz** [pkamb/PowerKey#47]
I bought this because karabiner doesn't work with Sierra. I used to use karabiner to make backslash do forward delete. I like the concept of your app but it is way too slow. To delete more than one letter I have to tap and hold for each letter which is painful. Is there any way you can make this app work faster?

**Comment by pkamb** [comment]
The delay you describe is caused by Apple's special treatment of the Power key (as well as a few other keys such as Caps Lock). The Power key requires a hard press compared to other keys, shuts the computer off if held down, etc.

We unfortunately don't currently have a way to get around those limitations. #1 

Remapping the standard backslash key would avoid all the issues mentioned above, but as you mentioned Karabiner does not currently work with Sierra: https://github.com/tekezo/Karabiner/issues/660

Adding support for remapping other keys is a bit outside the scope of PowerKey. Sorry for the app's limitations, and please send an email if you're not going to use PowerKey and would like a refund.

**Comment by harvestnz** [comment]
Thanks for the speedy response. That’s what I figured. $5 is nothing and I will use it until karabiner is fixed

Regards

Peter Munn  Managing Director

Harvest Electronics
+64 6 370 1991
PO Box 446 | 10 Pragnell Street
Masterton 5810 | New Zealand
[cid:E6C2D4C9-C387-4AF1-8AE3-B272FECEDCD1@win.harvest.com]

On 20/10/2016, at 9:33 AM, Peter Kamb <notifications@github.com<mailto:notifications@github.com>> wrote:


The delay you describe is caused by Apple's special treatment of the Power key (as well as a few other keys such as Caps Lock). The Power key requires a hard press compared to other keys, shuts the computer off if held down, etc.

We unfortunately don't currently have a way to get around those limitations. #1<https://github.com/pkamb/PowerKey/issues/1>

Remapping the standard backslash key would avoid all the issues mentioned above, but as you mentioned Karabiner does not currently work with Sierra: tekezo/Karabiner#660<https://github.com/tekezo/Karabiner/issues/660>

Adding support for remapping other keys is a bit outside the scope of PowerKey. Sorry for the app's limitations, and please send an email if you're not going to use PowerKey and would like a refund.
