### ISSUE TITLE
Inconsistent delete behaviour

### ISSUE THREAD

**Issue by efinlay24** [pkamb/PowerKey#58]
Hi,

Tried out PowerKey on macOS Sierra v10.12.5 - MacBook Pro (Retina, 13-inch, Early 2015.

I get inconsistent behaviour with the power key bound to Delete - sometimes it'll delete one character, but then further presses will do nothing. A single press will sometimes work but with a long delay - other times, nothing happens at all. Rapid repeated presses never seem to work successfully, or might sometimes only delete one character. Holding down the key sends it to sleep, which I think is expected.

It kinda feels like some default macOS power button shortcut is overriding PowerKey, but I don't know macOS well enough to say for sure.

Any ideas?

Happy to send further info if it helps. :)

**Comment by pkamb** [comment]
Yeah, this is definitely an issue with the power key when remapped, and it's unlikely we'll be able to fix it completely.

I find that it's best to use a firm tap at a regular cadence. You should tap slightly slower than you might normally tap another key to repeat it, because quick successive repeats are ignored by the system. And use a firm tap, because the system also ignores light/quick taps of the key.

More info here:
https://github.com/pkamb/PowerKey/issues/1
